# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '8page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from webcam import Ui_Webcam
import pymysql
import os

def connectDB():
    host="database-1.cb5pctivsgrb.us-east-1.rds.amazonaws.com"
    username="root"
    port=3306
    database="log-in"
    password="ksc2021583"

    conn=pymysql.connect(host=host,user=username,password=password,db=database,port=port)
    return(conn)

def disconnectDB(conn):
    conn.close()
    
def createFolder(directory):
    try:
        if not os.path.exists(directory):
            os.makedirs(directory)
    except OSError:
        print('Error: Creating directory. ' + directory)

def findnumber(db_name,db_phonenumber):
    sql2="SELECT memberID, name FROM memberdata where name ="+"'"+db_name+"'" "AND phonenumber ="+"'"+ db_phonenumber+"'"   
    conn2 = connectDB()
    curs2 = conn2.cursor()
    print(db_name)
    curs2.execute(sql2)  
    
    result=curs2.fetchone()
    print(result)
    print(int(result[0]))
    #print(str(result[1]))
        
    ## 이미지저장경로 설정, 컴퓨터에 맞게 변경필요
    #route='/Users/admin/Documents/GitHub/Pyqt5-facerecog-kiosk/image/'
    #routenumber=str(result[0])
    #createFolder(route+str(result[1])+str(result[0]))
        
    curs2.close()
    disconnectDB(conn2)

    
class Ui_register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Ui_register")
        MainWindow.resize(629, 652)
        self.window = MainWindow
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #사진촬영버튼
        self.pushbutton = QtWidgets.QToolButton(self.centralwidget)
        self.pushbutton.setGeometry(QtCore.QRect(230, 470, 151, 91))
        self.pushbutton.setObjectName("pushbutton")
        self.pushbutton.clicked.connect(self.take_pic)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 540, 121, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.close_window)
        
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 540, 121, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(110, 110, 431, 61))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_1.textChanged.connect(self.lineEdit_1changed)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 170, 431, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.textChanged.connect(self.lineEdit_2changed)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 230, 431, 61))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.textChanged.connect(self.lineEdit_3changed)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 290, 431, 61))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.textChanged.connect(self.lineEdit_4changed)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 350, 431, 61))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.textChanged.connect(self.lineEdit_5changed)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 410, 431, 61))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.textChanged.connect(self.lineEdit_6changed)
        
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(120, 110, 221, 71))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 170, 381, 71))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 230, 381, 71))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 290, 341, 71))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 350, 381, 71))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 410, 381, 71))
        self.label_6.setObjectName("label_6")
        
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 0, 256, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 350, 381, 71))
        self.label_5.setObjectName("label_5")
        self.lineEdit_6.raise_()
        self.pushbutton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.textBrowser.raise_()
        self.lineEdit_1.raise_()
        self.label_1.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def take_pic(self):
        self.picture_window = QtWidgets.QMainWindow()
        self.picture= Ui_Webcam()
        self.picture.setupUi(self.picture_window)
        self.picture_window.show()
        
        #DB연결
        
        db_name=self.lineEdit_1.text()
        password1=self.lineEdit_2.text()
        password2=self.lineEdit_3.text()
        db_birthdate=self.lineEdit_4.text()
        gender=self.lineEdit_5.text()
        db_phonenumber=self.lineEdit_6.text()
        
        sql="INSERT INTO memberdata ( name, password, birthdate, gender, phonenumber) VALUES ( %s, %s, %s, '%s', %s)"
       
        if password1==password2:    
            if gender=="여":
                db_gender=False
            elif gender=="남":
                db_gender=True
                   
            db_password=password1
            conn = connectDB()
            curs = conn.cursor()
            
            val=( db_name, db_password, db_birthdate, db_gender, db_phonenumber)
            
            curs.execute(sql,val)
            conn.commit()
            
           
        else:
            self.lineEdit_1.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")                
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_6.setText("")
        
   
        sql2="SELECT memberID, name FROM memberdata where name ="+"'"+db_name+"'" "AND phonenumber ="+"'"+ db_phonenumber+"'"   
        
        print(db_name)
        curs.execute(sql2)  
    
        result=curs.fetchone()
        
        ## 이미지저장경로 설정, 컴퓨터에 맞게 변경필요
        route='/Users/admin/Documents/GitHub/Pyqt5-facerecog-kiosk/image/'
        db_photoaddress=route+str(result[1])+str(result[0])
        createFolder(db_photoaddress)
        
        ##경로 photoaddress에 입력
        sql2="UPDATE memberdata SET photoaddress = %s WHERE memberID = %s"
        val2=(db_photoaddress,result[0])
        curs.execute(sql2,val2)
        conn.commit()
        curs.close()
        conn.close()
        
        
    def close_window(self):
        self.window.close()
        
    def lineEdit_1changed(self):
        if self.lineEdit_1:
            self.label_1.setVisible(False)
    
    def lineEdit_2changed(self):
        if self.lineEdit_2:
            self.label_2.setVisible(False)
            
    def lineEdit_3changed(self):
        if self.lineEdit_3:
            self.label_3.setVisible(False)
    
    def lineEdit_4changed(self):
        if self.lineEdit_4:
            self.label_4.setVisible(False)        
    
    def lineEdit_5changed(self):
        if self.lineEdit_5:
            self.label_5.setVisible(False)
    
    def lineEdit_6changed(self):
        if self.lineEdit_6:
            self.label_6.setVisible(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushbutton.setText(_translate("MainWindow", "사진촬영"))
        self.pushButton_2.setText(_translate("MainWindow", "이전"))
        self.pushButton_3.setText(_translate("MainWindow", "처음으로"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#b5b5b5;\">비밀번호를 입력해주세요</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#b5b5b5;\">비밀번호를 다시 입력해주세요</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#b5b5b5;\">생년월일을 입력해주세요</span><span style=\" font-size:12pt; color:#b5b5b5;\">(ex:19990909)</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#b5b5b5;\">휴대폰번호를 입력해주세요</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">회원가입</span></p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#b5b5b5;\">이름을 입력해주세요</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#b5b5b5;\">성별을 입력해주세요(ex 남/여)</span></p></body></html>"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_register()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
